#!/usr/bin/env python

Import('env')

qns_env = env.Clone()
qns_env.add_source_files(env.modules_sources, "quark_api.cpp")
qns_env.add_source_files(env.modules_sources, "register_types.cpp")

qns_env.Append(CPPPATH=['#modules/quark_api/include/'])
